{% set name = "ragel" %}
{% set version = "6.7" %}
{% set hash_type = "sha256" %}
{% set hash_val = "46df8e3f117a730f8896061c95ea8e8f53e9789cb053c2eea047833724fd7a30" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{version }}.tar.gz
  url: https://www.colm.net/files/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patches:
    # Fix compiler errors (unqualified lookup of 'compare' and 'setiosflags' functions).
    # Source: https://trac.macports.org/browser/trunk/dports/lang/ragel?rev=94741&order=name
    - patches/cxx_syntax.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain

about:
  home: https://www.colm.net/open-source/ragel/
  license: GPLv2
  license_file: COPYING
  summary: Ragel State Machine Compiler
  description: |
    Ragel provides a very flexible interface to the host language that attempts
    to place minimal restrictions on how the generated code is integrated into
    the application. The generated code has no dependencies.

extra:
  recipe-maintainers:
    - rolando
