{% set name = "ragel" %}
{% set version = "6.9" %}
{% set hash_type = "sha256" %}
{% set hash_val = "6e07be0fab5ca1d9c2d9e177718a018fc666141f594a5d6e7025658620cf660a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{version }}.tar.gz
  url: https://www.colm.net/files/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patches:
    - patches/0001-Fix-undeclared-setiosflags-function.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain

about:
  home: https://www.colm.net/open-source/ragel/
  license: GPLv2
  license_file: COPYING
  summary: Ragel State Machine Compiler
  description: |
    Ragel provides a very flexible interface to the host language that attempts
    to place minimal restrictions on how the generated code is integrated into
    the application. The generated code has no dependencies.

extra:
  recipe-maintainers:
    - rolando
