travis:
  secure:
    BINSTAR_TOKEN: lRqjN1Ss74mFQ4Rjg7bv543AFe3eJSysP+66e1HDGUuynHCbh19bc3bFPNcRLcmoPAcMFBnLjG+g8tVKFD5J3nIN9PzkoF2y6wxD8RVmoO81V/vlZezrAzXBe1/KSlwepOce4THj4Ia3pv6HNte277C3xPaVG/BeYS6eMWm1FcGC4D1d2uje8mxt3I5KkEuWqIUwmU832cIuMvEY3CD9xcGPTg0JxNOx7yizRx+tvzQigLRZpq/bBB4OnORdPBE+HkDbHdS53tMQr4v7GgBB2mCHYn3ksVTBrmC2UQuOgOQLZlsvc65q3v1/4ncx/p7aLl/CKnKhw2IVpzCeTatcoNHmUabP4icTdwNcaM6uymI4nOJ05sGB5tyx3WunW2nEcma8dQOglnXM5LkYIyyh+g/Z/hhCsREtKJBtEH7cSlanCOisBs9DZVAqNVy1j7/sxmQZU1t8qNVl2jJ0cN736ST+4LW1QDQKUhqARS+UrI122Wl4wq2xdHErAz4wcTLNJ+AK/ea8ekkvYPvx69EKlOtwKGYFBB8K0ey/ZeTyGFr5ciXtPn4Hb6ACPdcK8W5QhyWQTBkIZgEMKTSoW29gtBffj3Ky3dzTomUDugEi6WSp45RcTwSoOfmzixnXGynaTkfP2/gs5AEdKQryAnvQzcdisc4EvOw7lGYRdcFU2kA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
