travis:
  secure:
    BINSTAR_TOKEN: LtSk5rxjdqrpjsyoWIBTNKiRAz2z/WkkZyOPPYpS3hTgtiB/0C6EdFobqMXAuVYyXMXOhaYEcCXEqo+ScMmjVRXTGuSI/o3FyufNTPz8il02J2hs8MCzfnVWv/WX4BK1kigOWYhnyPl963RZoFAQpN2gLioeN/HJVPCokr9XfeB5SfWNT3krIa8Mbhdr3sXBT+4jApx/JyMAFgVJ+3u+IeQHWbWrMhzU3Slm/F7MiNzw6On0ce5v2b4jw/0VpXtqnTUkanYe6aSRzi5lb2+53UDcftcRfZAULcvDiGSOoDfVN2/Z9XSksUWo4rFzs1zP8Bxzah8rpQBtTqZSpopoH3fqzbFTAJPRnebLbWUC7P0KvYx99DR+RdVzy2W+h+GUavSm7ZscwwD4GehrY+Y16YOpGGvXQR6Pqz5260GVxKsrEjKPqSIiIRVDgW93kT4FGFcOl/TH9+q52WMajEYcpYiAk05E9G6fQGbllrbC+IlDWmZqPtMFluH0a9tRW2XIdylsZMkSezjwOSLNAEa+z2APlywMGn/o9FoLbJg8kUN5JSW3QNWGSBrF2VNJ45OZYzzzbWZqK4g5VHo3HXtjRTP77FFuWsWTGRTb9Okn3YyYXhXw66hgao8Dk/cZp9Uz7cGQQzf1DeNsSPilxb9Zqd4ndz61f9fIETTuVb62FRI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
